#define PERIODIC 
#define PMGRID 512
#define PEANOHILBERT 
#define WALLCLOCK 
#define MYSORT 
#define NO_ISEND_IRECV_IN_DOMAIN 
#define FIX_PATHSCALE_MPI_STATUS_IGNORE_BUG 
#define NOTYPEPREFIX_FFTW 
#define DEBUG 
#define DISTORTIONTENSORPS 
#define OUTPUT_DISTORTIONTENSORPS 
#define OUTPUT_TIDALTENSORPS 
#define CAUSTIC_FINDER 2
#define OUTPUT_LAST_CAUSTIC 
#define COMOVING_DISTORTION 
